import React from 'react';
import type { Metadata } from "next";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Geist, Geist_Mono, Gothic_A1 } from "next/font/google";
import "./globals.css";

const gothic_a1 = Gothic_A1({
    variable: "--font-gothic-a1",
    subsets: ["latin"],
    weight: ['400', '500']
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
